FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

LABEL maitainer="Alexander Kalinovsky <a.kalinovsky@onesoil.ai>"


RUN mkdir -p /workspace
WORKDIR /workspace
COPY pip-requirements.txt /workspace

RUN apt-get update && apt-get install -y locales \
    && locale-gen en_US.UTF-8 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive
ENV TZ Europe/Minsk


# (0) add ubuntu-gis repository & install GDAL & basic utils
RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common \
    && add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        protobuf-compiler \
        libprotoc-dev \
        gdal-bin \
        libspatialindex4v5 \
        libspatialindex-c4v5 \
        libspatialindex-dev \
        libpython3.6 \
        python3-pip \
        python3-setuptools \
        python3-wheel \
        less \
        unzip \
        htop \
        mc \
        libice6 \
        libsm6 \
        iputils-ping \
    && pip3 install pip -U \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# (1) add DL runtime libraries: onnx-runtime
RUN pip3 --no-cache-dir install -r /workspace/pip-requirements.txt \
    && pip3 install onnxruntime-gpu \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*


# FIX libraries
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libcublas9.1 \
        libcudart9.1 \
        libgomp1 \
    && pip3 --no-cache-dir install numpy -U \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*


# add pytorch-cpu
RUN pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu \
    -f https://download.pytorch.org/whl/torch_stable.html \
