FROM nvidia/cuda:10.0-base-ubuntu18.04

LABEL maitainer="Alexander Kalinovsky <a.kalinovsky@onesoil.ai>"


RUN mkdir -p /workspace
WORKDIR /workspace
COPY pip-requirements.txt /workspace


ENV DEBIAN_FRONTEND=noninteractive
ENV TZ Europe/Minsk
#echo "Europe/Minsk" > /etc/timezone && \


# (CPU.1) basic setup python3.7
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-dev \
    python3-pip \
    python3-tk \
    python3-setuptools \
    python3-wheel \
    software-properties-common \
    build-essential \
    autoconf \
    libtool \
    pkg-config \
    less \
    curl \
    wget \
    mc \
    htop \
    tmux \
    unzip \
    sshfs openssh-client \
    rsync \
    iotop \
    bash-completion \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1 \
    && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 \
    && pip install setuptools -U \
    && pip install wheel -U \
    && pip completion --bash >> ~/.bashrc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# (CPU.2) setup GDAL & gis libs
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    libgdal-dev \
    gdal-bin \
    libspatialindex4v5 \
    libspatialindex-c4v5 \
    libspatialindex-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# (CPU.3) install python dependencies
COPY pip-requirements.txt /workspace
RUN pip --no-cache-dir install \
    -r /workspace/pip-requirements.txt


# (CPU.4) install gsutils for Google-Cloud-Platform
RUN echo "deb https://packages.cloud.google.com/apt cloud-sdk main" \
    | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
    && apt-get update \
    && apt-get install -y --no-install-recommends google-cloud-sdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*



# ---( GPU/CUDA )--------------------------------

# (GPU.1) setup basic env for CUDA
ENV PATH=${HOME}/bin:${PATH}:/usr/local/cuda/bin
ENV LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib:${LD_LIBRARY_PATH}
ENV CUDA_HOME=/usr/local/cuda


# (GPU.2) install tensorflow
RUN pip --no-cache-dir install \
    tensorflow-gpu \
    keras
